





parameters: 
  description: "A theoretical example where the second source has zero unique information about the target. The first source has some unique information, and there is also some redundant and synergistic information."
  n: 1000000
  p: 10 #The same feature dimension for all varaibles
  noise_std: 1.0
  seed: 56
  bias_correction: True
  results_dir: "/home/ohadshee/Desktop/Thesis_Ohad_Sheelo/Simulations/Theoretical_Examples/RVs_Story/results_rvs"