





parameters: 
  description: "A theoretical example where the second source has zero unique information about the target. The first source has some unique information, and there is also some redundant and synergistic information."
  n_samples: 100000000
  p: 10 #The same feature dimension for all varaibles
  noise_std: 1.0
  seed: 42
  bias_correction: True
  results_dir: "/home/ohadshee/Desktop/Thesis_Ohad_Sheelo/Simulations/Theoretical_Examples/RVs_Story/results_rvs" #For RVs simulations
  n_epochs: 30
  batch_size: 128
  n_flows: 4
  bits: True
  device: "cpu"
  methods: ['tilde', 'delta', 'idep']


covariance:
  p_scale: 0.3
  q_scale: 0.5
  r_scale: 0.5
  dx1: 50
  dx2: 55
  dt: 35
  n_trials: 20
  methods: ['tilde', 'delta']
  output_dir: "/home/ohadshee/Desktop/Thesis_Ohad_Sheelo/Simulations/Theoretical_Examples/Covariance/results_covariance"
