simulation: logdet bias comparison for M7 and M8 models
seed: 1
N_samples_values:
- 500
- 2500
- 5000
p_values:
- - 10
  - 10
  - 10
- - 20
  - 30
  - 40
- - 50
  - 75
  - 100
p_scale: 0.0
q_scale: 0.0
r_scale: 0.0
