device: cuda
seed: 1
n_samples: 500
n_trials: 1000
p_scale: 0.15
q_scale: 0.25
r_scale: 0.35
bias_correction: false
on_covariance: shrunk_cov
alpha: 1.0
bias_method:
- bootstrap
n_bootstraps: 400
p_values:
- - 70
  - 71
  - 100
N_values:
- 300
