simulation: logdet bias comparison for M7 and M8 models
seed: 1
N_samples_values:
- 500
- 1000
- 2000
p_values:
- - 5
  - 5
  - 7
- - 10
  - 10
  - 10
- - 20
  - 30
  - 40
- - 50
  - 75
  - 100
- - 100
  - 105
  - 120
p_scale: 0.15
q_scale: 0.25
r_scale: 0.35
