simulation: logdet bias comparison for M7 and M8 models
seed: 1
N_samples_values:
- 200
- 300
- 400
p_values:
- - 30
  - 30
  - 30
- - 40
  - 50
  - 50
- - 51
  - 52
  - 53
p_scale: 0.0
q_scale: 0.0
r_scale: 0.0
