simulation: logdet bias comparison for M7 and M8 models
seed: 1
N_samples_values:
- 200
- 300
- 500
p_values:
- - 30
  - 40
  - 50
- - 50
  - 50
  - 50
- - 40
  - 50
  - 100
p_scale: 0.0
q_scale: 0.0
r_scale: 0.0
