device: cpu
seed: 1
n_trials: 500
bias_correction: true
lr_type: ridge
lasso_alpha: 0.1
on_covariance: 'False'
alpha: 2
bias_method:
- bootstrap
n_bootstraps: 20
mi_type: whiten
bi_mi_type: whiten
n_perm: 20
normalization: 'True'
p_scale: 0.05
q_scale: 0.65
r_scale: 0.75
mode: m8_side
delta: 0.2
N_values:
- 100
- 120
- 150
p_values:
- - 20
  - 25
  - 35
- - 40
  - 20
  - 20
- - 30
  - 30
  - 30
- - 35
  - 40
  - 20
