simulation: logdet bias comparison for M7 and M8 models
seed: 1
N_samples_values:
- 10
- 20
- 30
p_values:
- - 1
  - 1
  - 1
- - 2
  - 2
  - 2
- - 2
  - 3
  - 2
p_scale: 0.0
q_scale: 0.0
r_scale: 0.0
