N_P_variations:
  N_values: [10]
  p_values: [[1,1,1]]


Mutual_Information_Simulation:
  device: 'cpu'
  seed: 1
  n_trials: 10
  analytic_bias_correction: False
  resample_bias_correction: False
  lr_type: 'ridge' # options: 'ols', 'ridge', 'lasso'
  lasso_alpha: 0.1 # only used if lr_type is 'lasso
  on_covariance: 'False' # options: 'False', 'ledoit_wolf', 'shrunk_cov' , 'oas'
  alpha : 0.5 # only used if on_covariance is 'shrunk_cov'
  bias_method: ['bootstrap'] # options: ['bootstrap', 'jackknife', 'analytic'] 
  n_bootstraps: 20
  mi_type: 'lr' # options: 'whiten', 'lr'
  bi_mi_type: 'whiten'
  normalization: 'True'

0=Mutual_Information_Simulation:
  p_scale: 0.0
  q_scale: 0.0
  r_scale: 0.0



0<Mutual_Information_Simulation:
  p_scale: 0.15
  q_scale: 0.25
  r_scale: 0.35
