functions:
  target_extraction: nsd_voxel_target
  sources_extraction: nsd_sources
  choose_layer: specific_layer_index
  feature_extraction: nsd_feature_extraction
  preprocess: null
  feature_manipulation: pca_each_source
  pid_calculation: pid_calc
  pid_report: print_pid_mi

target_kwargs:
  voxel_index: 0
  subj_id: subj01
  hdf_path: /groups/golan_neurogroup/bml_group/datasets/nsddata/nsddata_stimuli/stimuli/nsd/nsd_stimuli.hdf5
  pkl_info_path: /groups/golan_neurogroup/bml_group/datasets/nsddata/nsddata/experiments/nsd/nsd_stim_info_merged.pkl
  neural_data_path: /groups/golan_neurogroup/bml_group/datasets/nsddata/otc_betas/otc_betas_per_stim/subj01_OTC_betas_per_stimulus.zarr
  n_images: 200

sources_kwargs:
  model_name_1: alexnet_random
  model_name_2: resnet18_random

choose_layer_kwargs:
  X1_index: 0
  X2_index: 0

feature_extraction_kwargs:
  batch_size_process: 4
  batch_size_dataloader: 4

preprocess_kwargs: {}

feature_manipulation_kwargs:
  n_components: 20

pid_kwargs:
  method: tilde
  rng_seed: 56
  config:
    device: cpu
    bias_correction: True

report_kwargs: {}
