
N_P_variations:
  N_values: [200,300,500]
  p_values: [[30,40,50],[50,50,50],[40,50,100]]


logdet_simulation:
  device: 'cpu'
  seed: 1
  n_samples: 100
  n_trials: 200
  p_scale: 0.0
  q_scale: 0.0
  r_scale: 0.0
  bias_correction: False
  bias_method: ['analytic'] # options: ['bootstrap', 'jackknife', 'analytic'] or 
  n_bootstraps: 400
  


Mutual_Information_Simulation:
  device: 'cpu'
  seed: 1
  n_trials: 100
  analytic_bias_correction: True
  resample_bias_correction: False
  lr_type: 'ridge' # options: 'ols', 'ridge', 'lasso'
  lasso_alpha: 0.1 # only used if lr_type is 'lasso
  on_covariance: 'False' # options: 'False', 'ledoit_wolf', 'shrunk_cov' , 'oas'
  alpha : 0.5 # only used if on_covariance is 'shrunk_cov'
  bias_method: ['bootstrap'] # options: ['bootstrap', 'jackknife', 'analytic'] 
  n_bootstraps: 20
  mi_type: 'whiten' # options: 'whiten', 'lr'
  bi_mi_type: 'whiten'
  n_perm : 50
  normalization: 'True' #If we need to whiten, is it already whiten or leave it not whiened. Options: 'True' (already whitened), 'False' (leave not whitened), 'whiten_ver' (whitened with the same method as the one used for the mi estimation)
  p_scale: 0.35
  q_scale: 0.45
  r_scale: 0.50

0=Mutual_Information_Simulation:
  p_scale: 0.0
  q_scale: 0.0
  r_scale: 0.0



0<Mutual_Information_Simulation:
  p_scale: 0.35
  q_scale: 0.55
  r_scale: 0.45


LR_Idep_Simulation:
  device: 'cuda'
  seed: 1
  n_samples: 500
  n_trials: 1000
  p_scale: 0.15
  q_scale: 0.25
  r_scale: 0.35
  lr_type: 'ols' # options: ['ols', 'ridge', 'lasso']
  bias_correction: False,
  'on_covariance': False,
  bias_method: ['bootstrap'] # options: ['bootstrap', 'jackknife', 'analytic'] s
  n_bootstraps: 400