
N_P_variations:
  N_values: [800,1000,3000]
  p_values: [[100,105,120],[150,150,150],[150,160,200]]


logdet_simulation:
  device: 'cuda'
  seed: 1
  n_samples: 1000
  n_trials: 1000
  p_scale: 0.0
  q_scale: 0.0
  r_scale: 0.0
  bias_correction: False
  bias_method: ['analytic'] # options: ['bootstrap', 'jackknife', 'analytic'] or 
  n_bootstraps: 400
  


Mutual_Information_Simulation:
  device: 'cuda'
  seed: 1
  n_samples: 500
  n_trials: 500
  p_scale: 0.0
  q_scale: 0.0
  r_scale: 0.0
  bias_correction: True
  bias_method: ['bootstrap'] # options: ['bootstrap', 'jackknife', 'analytic'] s
  n_bootstraps: 20
