
N_P_variations:
  N_values: [500,5000]
  p_values: [[10,10,10]]


logdet_simulation:
  seed: 1
  n_samples: 1000
  n_trials: 1000
  p_scale: 0.35
  q_scale: 0.25
  r_scale: 0.15
  bias_correction: True


Mutual_Information_Simulation:
  seed: 1
  n_samples: 1000
  n_trials: 1000
  p_scale: 0.0
  q_scale: 0.0
  r_scale: 0.0
  bias_correction: True